# Generated by Django 4.0.5 on 2022-06-16 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='наименование')),
                ('title', models.TextField(blank=True, verbose_name='Описание')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('link', models.TextField(verbose_name='Ссылка')),
                ('created_on', models.DateTimeField(verbose_name='ДатаСоздания')),
            ],
        ),
    ]
